name: Setup IDAES
description: Install IDAES and extensions
input:
  python-version:
    description: Python version
    required: true
    default: '3.7'
  install-target:
    description: 'Command-line arguments and options to pass to the install command, e.g. pip install'
    required: true
  install-command:
    description: 'Command to use to install `install-target`'
    required: false
    default: pip --no-cache-dir install --progress-bar off
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Update pip and other packaging tools
      run: |
        ${{ inputs.install-command }} pip setuptools wheel
    - name: Install idaes and dependencies
      run: |
        ${{ inputs.install-command }} ${{ inputs.install-target}}
        idaes --version
    - name: Install extensions
      run: |
        idaes get-extensions --verbose
        # add bin directory to $PATH (only valid for subsequent steps)
        echo "$(idaes bin-directory)" >> $GITHUB_PATH
    - name: Test access to executables
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
            ipopt.exe -v
        else
            ipopt -v
        fi
