name: PR (integration)

on:
  pull_request:
    types: [assigned]

jobs:
  check-skip:
    name: check if integration tests should run
    runs-on: ubuntu-latest
    if: "contains(github.event.sender.login, 'idaes-')"
    steps:
      - name: notify
        run: echo "The integration tests will run"
  pytest:
    name: Integration tests (py${{ matrix.python-version }}/${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: [check-skip]
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
        os:
          - ubuntu-18.04
          - windows-latest
    steps:
      - name: Display debug info
        run: |
          echo '${{ toJSON(matrix) }}'
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up idaes
        uses: ./.github/actions/setup-idaes
        with:
          install-target: '.'
      - name: Run pytest (not integration)
        run: |
          pytest -m 'integration'
  pytest-coverage:
    name: Run pytest (complete) with coverage report
    runs-on: ubuntu-latest
    needs: [check-skip]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Set up idaes
        uses: ./.github/actions/setup-idaes
        with:
          install-target: -r requirements-dev.txt
      - name: Run pytest (complete) with cov
        run: |
          pytest --cov
      - name: Upload coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash)
